#!/bin/bash
#SBATCH -J corr_pool_sim_2000                  # Job name
#SBATCH -o /home/jw2529/group-testing-with-household-correlation/scripts/test_%j.out  # output file (%j expands to jobID)
#SBATCH -e /home/jw2529/group-testing-with-household-correlation/scripts/test_%j.err                  # error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                      # Request status by email
#SBATCH --mail-user=jw2529@cornell.edu.       # Email address to send results to.
#SBATCH -N 1                                 # Total number of nodes requested
#SBATCH -n 24                                 # Total number of cores requested
#SBATCH --get-user-env                       # retrieve the users login environment
#SBATCH --mem=32678m                           # server memory requested (per node)
#SBATCH -t 168:00:00                           # Time limit (hh:mm:ss)
#SBATCH --partition=default_partition             # Request partition
#SBATCH --gres=gpu:0                 # Type/number of GPUs needed
/home/jw2529/group-testing-with-household-correlation/scripts/test.sh